### ISSUE TITLE
Not extracting library authors, narrators or book numbers

### ISSUE THREAD

**Issue by joonaspaakko** [joonaspaakko/audible-library-extractor#105]
Basically all features that have to do with authors and narrators and book numbers are not working. 

> Book numbers seem to be processed as if it's another series the book is a part of and there aren't any book numbers in the series sub page.

However, thankfully the book numbers are intact in the book title as well as in the `My books in the series` list, so the gallery remains somewhat usable:
<img src="https://user-images.githubusercontent.com/1164476/191932164-b690982d-80ad-4490-b8aa-0488202a3136.png">

Aside from that, you have to wait for the next version (0.2.9). I could perhaps make a hotfix build for this if requested, if you can't wait for the next official release. This hotfix would have to be installed as a developer extension outside of the chrome web store.

**Comment by moddimoddi** [comment]
I have the same problem, no authors or narrators!

**Comment by joonaspaakko** [comment]
Yea, unfortunately because this issue came about due to changes on the Audible website, there's no doubt that every user will have this issue.
