### ISSUE TITLE
Export No Longer Working

### ISSUE THREAD

**Issue by dreamweaver529** [joonaspaakko/audible-library-extractor#122]
This has worked for a long time, then starting 4/26/2023 it stopped working. I just bought Torrent Witches Cozy Mysteries Complete Box Set: Books 1-10.

I've "Removed all extracted data" and let the extractor run all night. It gets as far as "Fetching series order for books in series..."

The last error showed up right as it froze
![image](https://github.com/joonaspaakko/audible-library-extractor/assets/45337730/94cf7956-d4af-4cb5-be5a-5dc015f1e7f3)

**Comment by dreamweaver529** [comment]
It might help if I read more than the top post. I'm sorry.

I was using 0.2.8. After reading the other thread, I installed 0.2.9 and it worked like a charm.

Thanks for all your hard work. I was a nightmare not having this wonderful resource. So much better than annoying native to the site.

**Comment by joonaspaakko** [comment]
There's still a plethora of small issues in the 0.2.9 draft, specifically in the gallery. It's likely that anything that seems broken is on its way to be fixed, but feel free to report anything you find.

> For anyone else, until the new version actually comes out, installation instructions for the draft
> 1. [Download the 0.2.9 draft](https://github.com/joonaspaakko/audible-library-extractor/blob/master/audible-library-extractor-0.2.9.zip) (download icon on the right side). 
> 2. Go to the address: chrome:extensions (or: Window > Extensions)
> 3. Turn on the developer mode from the top right
> 4. Drag the downloaded .zip file in the browser window to install
