### ISSUE TITLE
Fetching series order for books in series...

### ISSUE THREAD

**Issue by Rokkmann** [joonaspaakko/audible-library-extractor#124]
The above step in "Library 1/2" always sticks for me on the last step which is 65/66. 

![image](https://github.com/joonaspaakko/audible-library-extractor/assets/62431516/286d03c6-b48b-4f1c-91e2-c6d29f188161)

I've let it sit for 10+ minutes and nothing, attempted redoing the extraction, nothing. 

Any ideas?

**Comment by joonaspaakko** [comment]
You should have better luck with the version 0.2.9 draft. You can find installation instructions here: https://github.com/joonaspaakko/audible-library-extractor/issues/87#issuecomment-1592510201
