### ISSUE TITLE
Language German "Beendet" English "Finished"

### ISSUE THREAD

**Issue by Kumskaka** [joonaspaakko/audible-library-extractor#125]
Hi, 
first thank you for your work.
Now my issue, some of my finished Books are marked with "finished" and some marked with gerrman word "Beendet".
My account is on Audible.de. Because of this the list are not showing the correct images.
Is their a way to change this behavior.

**Comment by Kumskaka** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Markus/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Markus/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



62 | Deal!: Du gibst mir,   was ich will | Deal! |   |   | Lernen Sie, wie   wenige Sekunden über große und kleine Vermögen entscheiden. Und wie man diese   wenigen Sekunden nutzt... | Jack Nasher | Jack Nasher | Erfolg im Beruf | Wirtschaft &   Karriere > Erfolg im Beruf | Wirtschaft &   Karriere | Erfolg im Beruf | 5h 59m | Beendet | 23.05.2013 | ABOD Verlag
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
61 | Ich finde dich | Ich finde dich |   |   | Natalie war die   Liebe seines Lebens. Doch sie hat ihn verlassen, hat wie aus dem Nichts einen   anderen Mann geheiratet... | Harlan Coben | Detlef   Bierstedt | Psychothriller | Krimis &   Thriller > Thriller | Krimis &   Thriller | Thriller | 10h 37m | Beendet | 10.03.2014 | Der Hörverlag
60 | Sein letzter Wille: Myron-Bolitar-Reihe 10 | Sein letzter Wille | Myron-Bolitar-Reihe (book 10) | 10 | Rockstar Lex und seine Frau Suzze führen eine äußerst   glückliche Ehe. Voller Vorfreude erwarten sie die baldige Geburt ihres ersten   Kindes... | Harlan Coben | Detlef Bierstedt | Literatur & Belletristik, Thriller | Krimis & Thriller > Thriller | Krimis & Thriller | Thriller | 10h 51m | Beendet | 11.11.2013 | Der Hörverlag
59 | Wer einmal lügt | Wer einmal   l&uuml;gt |   |   | Ein großes,   elegantes Haus in einem reichen Wohnviertel, ein teures Auto, zwei   wohlgeratene Kinder: Megan lebt den perfekten amerikanischen... | Harlan Coben | Detlef   Bierstedt | Literatur &   Belletristik, Thriller | Krimis &   Thriller > Thriller | Krimis &   Thriller | Thriller | 12h 8m | Finished | 07.03.2013 | Der Hörverlag
58 | Das Grab im Wald | Das Grab im Wald |   |   | Zwanzig Jahre ist es her, dass vier Jugendliche nachts in   einen Wald liefen. Zwei wurden kurz darauf brutal ermordet aufgefunden. Von   den anderen beiden fehlt seither jede Spur... | Harlan Coben | Detlef Bierstedt | Thriller | Krimis & Thriller > Thriller | Krimis & Thriller | Thriller | 12h 44m | Finished | 03.04.2009 | Audible Studios
57 | Kein böser   Traum | Kein   b&ouml;ser Traum |   |   | Grace Lawson   will nur die Schnappschüsse vom letzten Familienausflug durchsehen, als   plötzlich ihr ganzes bisheriges Leben aus den Fugen gerät... | Harlan Coben | Detlef   Bierstedt | Psychothriller | Krimis &   Thriller > Thriller | Krimis &   Thriller | Thriller | 12h 3m | Finished | 12.02.2009 | Audible Studios



</body>

</html>

**Comment by joonaspaakko** [comment]
Yea, should be doable. I think my only option is to put in a check to see if the word is `Beendet` and replace it with the word `Finished`, either when extracting that specific data point or just before opening the gallery.

Are you using the version 0.2.9 draft?

> The down side is that likely all languages have this problem and it only fixed is for German... And for some reason some of them do have `Finished`, so there is a change all of them could have that, which would potentially fix it for all languages, but since I have no books in the German Audible, I'm not sure I could ever figure it out.

**Comment by Kumskaka** [comment]
Hi, I use the 0.2.9 draft and English is always better for programming.

**Comment by joonaspaakko** [comment]
Alright, good.

I could've made it easy for you, that you just open the gallery and the data is rewritten, but I felt it was better to do it during the extraction, so in this particular case, it will take you a few extra steps to see if it fixes it.

So to try the updated draft, it's probably easiest if you bring over the existing data and do a new (partial) extraction. [I made a video of the process just in case](https://www.dropbox.com/s/o8iizn8wjmg3hvv/ALE-Beetend-to-Finished.mov?dl=0), but here are the steps:

1. Export raw data _(in extraction settings)_
2. In your Chrome extensions (`chrome:extensions`):
    1. Remove the extension
    2. Install the new draft [(audible-library-extractor-0.2.9.zip)](https://github.com/joonaspaakko/audible-library-extractor/raw/master/audible-library-extractor-0.2.9.zip)
 3. Import raw data _(in extraction settings)_
 4. Do extraction
     - After the partial extraction is done, it does the word replacement and opens the gallery
     
> Note, I misspelled the word `Beendet` in the project commit and video title, just ignore it, it's replacing `Beendet` in the code

**Comment by Kumskaka** [comment]
Thank you, it works fine.
