### ISSUE TITLE
All results from "The Great Courses" publisher are omitted

### ISSUE THREAD

**Issue by christianboyle** [joonaspaakko/audible-library-extractor#27]
Loving this project, thanks for open-sourcing it!

One small issue I've found is that all audiobook courses from [The Great Courses](https://www.audible.com/search?searchProvider=The+Great+Courses&ref=a_pd_Origin_c1_publisher&pf_rd_p=8a2752a8-601f-4465-b227-7e95d7917c27&pf_rd_r=MQ7MSHMM0Y4GJJBX92AT) are omitted from the results returned from the library extraction.

Any idea why that might be?

**Comment by joonaspaakko** [comment]
I have purposely weeded out podcasts, but the great courses books look like any regular book to me. The best I can think of is they have some common data point that causes the extraction to fail or just ignore the books. There is a chance that the attribute I'm using to check if it's a book or a podcast has something to do with it.

I'll see if I can figure something out before my next planned release. I'll get back to you if I need more info. In the mean time, can you post a link to one or two of these books that aren't coming through? It's better if they are plus catalog books.

**Comment by christianboyle** [comment]
I'm not sure how to determine if any of these are in the Plus Catalog, so I'll just list all of them (no Great Courses audiobooks are showing in my results currently):

- [The Great Ideas of Philosophy, 2nd Edition](https://www.audible.com/pd/The-Great-Ideas-of-Philosophy-2nd-Edition-Audiobook/B00DDVSD34?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [Great Mythologies of the World](https://www.audible.com/pd/Great-Mythologies-of-the-World-Audiobook/B013KRSIVC?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [Mysteries of Modern Physics: Time](https://www.audible.com/pd/Mysteries-of-Modern-Physics-Time-Audiobook/B00DDXP9YI?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [The Higgs Boson and Beyond](https://www.audible.com/pd/The-Higgs-Boson-and-Beyond-Audiobook/B00SJIXBP6?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [Understanding Complexity](https://www.audible.com/pd/Understanding-Complexity-Audiobook/1629976849?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [Stress and Your Body](https://www.audible.com/pd/Stress-and-Your-Body-Audiobook/B00DHQMKW0?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [No Excuses: Existentialism and the Meaning of Life](https://www.audible.com/pd/No-Excuses-Existentialism-and-the-Meaning-of-Life-Audiobook/B00DDY7SWS?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [Brain Myths Exploded: Lessons from Neuroscience](https://www.audible.com/pd/Brain-Myths-Exploded-Audiobook/B01NASOS26?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [Redefining Reality: The Intellectual Implications of Modern Science](https://www.audible.com/pd/Redefining-Reality-Audiobook/B00ZB7QIIU?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [Biology and Human Behavior: The Neurological Origins of Individuality, 2nd Edition](https://www.audible.com/pd/Biology-and-Human-Behavior-The-Neurological-Origins-of-Individuality-2nd-Edition-Audiobook/B00DG66SJW?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)
- [Origins of the Human Mind](https://www.audible.com/pd/Origins-of-the-Human-Mind-Audiobook/B00DH9TI5E?ref=a_library_t_c5_libItem_&pf_rd_p=85df3330-9dc4-4a45-ae69-93cc2fc25ca4&pf_rd_r=WTYSVSBKQX7X9NCYDQZT)

**Comment by joonaspaakko** [comment]
Hey @christianboyle, just wanted to inform you that I've traced down the source of the issue and you can expect the next release (v.0.2.5) to fix it. 

> My guesses have been on point this week. The extension looks for specific type of items from your library and these courses didn't fall under the existing conditions. They're marked as "lecture"...

I'm aiming to get it released by the end of the week. The dev release in Github will update as soon as it's pushed out but the official channels for Chrome and Firefox will take a day or five.

**Comment by christianboyle** [comment]
@joonaspaakko Awesome news, looking forward to it!

**Comment by christianboyle** [comment]
Very nice, can confirm it works as expected on my end with all 11 Great Courses books now returned when searching. Thanks again!

![2021-03-07_02-05-49PM](https://user-images.githubusercontent.com/1605754/110253142-61356d00-7f4e-11eb-82ee-56f14db35965.png)

**Comment by joonaspaakko** [comment]
Good. I actually never tested anything but the few Plus Catalog books I found from this page: [The Great Courses | Audible.com](https://www.audible.com/ep/the-great-courses)
