### ISSUE TITLE
Laggy / slow gallery (large libraries — sometimes) 

### ISSUE THREAD

**Issue by joonaspaakko** [joonaspaakko/audible-library-extractor#41]
It depends on what kind of computer you are using. You could see it happening on an old laptop or perhaps you don't see it at all. I'm seeing this on slightly older mobile devices when the library exceeds about 600 books. 

> It also depends on the size of the `current list`. As in if you filter your library to let's say 200-400 books, you probably won't have the issue.

- It basically lags when you do anything
- Scrolling
- Loading elements after scrolling
- Opening book details
- Everything just kind of takes its time
- The more books you add to an already laggy experience, the more it will lag.

----

**Fix?**

Right now the books are rendered once they enter the browser's viewport (visible area), which reduces the initial load (which is already terrible because of how the data is handled :/), but even after that, it still has to keep a lookout for a bunch of elements that have not yet passed through the viewport and that is the crux of the issue, as it gets pretty taxing after a certain point. 

The current idea is to implement `infinite scroll`, where these observable elements aren't created until you scroll to the bottom (or close enough). The elements would be added in chunks of 100 or something. So after ever 100 books it would have to load a hundred more. This solution would for the most part look and work the same as before, except it would be more performant.

> **One issue with this solution** is how right now when you open book details it changes the URL so you can send a link to that specific book in that specific context. I won't go into detail why, but that would likely have to be changed a little. Like when you open the link, it would instead show you that one book in some sort of isolated view, rather than how it's done right now where the browser scrolls to the book and opens its details. 
> 
> 1. I was thinking it would make sense to then perhaps remove the functionality that sets the URL param automatically and just have an icon that you could click to copy the URL if needed. This link would only contain the book and no other URL params. That would simplify it.
> 
> 2. Another possibility is that when you open a link with a `book` URL param, it would make a search using its `ASIN` (ID) so the only book you'd see on page load is this one. Then if you undo the search you could see all the rest of the books in that context. That way the link could still keep all the other URL params. Or maybe a more custom solution than just using the search?

**Comment by JKamsker** [comment]
Maybe even split up the json into chunks, so that the browser doesnt have to parse gigabytes of metadata at once :D

**Comment by joonaspaakko** [comment]
Fixed it according to the original plan, but went for a hybrid solution where vertical scrolling updates URL param `y` (as in vertical offset) and that determines how many books are rendered on page load. Or if book details are open in URL params `book`, that overrides the scroll distance and loads as many books as are needed to get to the book. 

> In my test before the fix, I used an Iphone 8 and a library with around 1000 books. It was almost unusable. Now it's very smooth

Pros:
- Faster load time of books when scrolling even on devices that didn't really feel sluggish before.

Cons:
- You may still get a laggy experience if you load the page from a URL that ends up loading too many books at once for your device to handle

- - - - 

At first when I was building this lazy load system I made it so that if you loaded a page with book details open, It would load one book and nothing else, but with a button that says "Expand view (200)" parenthesis had the number of books in the collection... and when you click it. it would show everything in the collection. This I thought was an ok compromise, however I changed my mind when I realized that backwards navigation (back button in the browser) would always reset the view and throw you to the top. This was super irritating and so this current solution ended up being the lesser evil... I suppose.
