### ISSUE TITLE
Extract Bookmarks and Notes?

### ISSUE THREAD

**Issue by gobbletown** [joonaspaakko/audible-library-extractor#51]
Would be great to pull out bookmarks and notes as well.

https://github.com/vatioz/AudibleBookmarks -- has an example.

Able to add as enhancement?

**Comment by joonaspaakko** [comment]
So I looked into this and I think I'm going to have to say it's either not possible or I don't have the know-how to do it.

First of all, all the data the extension scrapes is through the website and bookmark/note data is not available there. A cursory inspection of that other project tells me it extracts the bookmark information from the audio files, but according to it, the file has to be downloaded through one of the apps. My best guess is that if you get it through the website, the files don't contain the bookmark metadata, but it's injected in the file if you download it through the apps. 

Some of my thoughts: 

1. If the files need to be downloaded through the app(s), it's not possible for the extension to download them through the website and check the files automatically.
2. Even if it was possible and I am able to extract the metadata, there's still no way to see if a file has bookmarks/notes without downloading the file.
	- Let’s say you have a library with around `500 books` and they are all `10 hours` long, which could be around `300MB`. With a `100Mbps` internet it would take around `25 seconds` to download each file and `25sec * 500 = 12500sec` or `~3,5 hours`, and that would be too much. It's almost too much to ask for people to keep the extraction tab active for the current ~2-15 minutes...
3. But ok... what if this functionality would require you to download the files manually through your Audible app(s), just like in this other project and feed them to the extension, you know, like the way you attach files in an email.
4. This could perhaps work, but so far I haven't been able to extract bookmark/notes metadata from any files. [jDataView](https://github.com/jDataView/jDataView) looked like a promising tool for making it happen, but in my tests, if the bookmark metadata is there, I couldn't find it. This stuff kinda goes above my head.
5. Oh, and... if the extension should also extract the clips, it would have to convert the AAX files to mp3's + slice and dice the original file down to the bookmark clip(s). This I think would also be a bit of a tall order to do in the browser without the help of a server. Though I'm not sure.

All in all, this seems like it would be as big of a project as the extension has been so far. I think I'm going to have to say no can do right now. It's not a hard no, but I would not hold my breath waiting for it.

If [vatioz/AudibleBookmarks](https://github.com/vatioz/AudibleBookmarks) can export the notes in a sensible way, it could be possible to import that to the extension in a way that makes more sense than building the same functionality into the extension.
