### ISSUE TITLE
Extraction can not complete (stuck on Ready Player One)

### ISSUE THREAD

**Issue by CatHerderCam** [joonaspaakko/audible-library-extractor#66]
bug for Audible Library Extractor v0.2.6 public release.

Over the past few weeks, I have not been able to finish an extraction. It seams that it is hanging on "fetching additional data from store pages..." explicetly on Ready Player One. Looking at the console the only things I see is the errors listed below, and they seem to happen on every call, not just this one book.

```
audible-library-extractor-content-script.js:2 TypeError: Cannot read properties of null (reading 'getAttribute')
    at audible-library-extractor-content-script.js:2
    at NodeList.forEach (<anonymous>)
    at a.getDataFromCarousel (audible-library-extractor-content-script.js:2)
    at audible-library-extractor-content-script.js:2
    at Object.step (audible-library-extractor-content-script.js:2)
    at audible-library-extractor-content-script.js:2
```

```
audible-library-extractor-content-script.js:2 axios caught an error TypeError: Cannot read properties of null (reading 'getAttribute')
    at audible-library-extractor-content-script.js:2
    at NodeList.forEach (<anonymous>)
    at a.getDataFromCarousel (audible-library-extractor-content-script.js:2)
    at audible-library-extractor-content-script.js:2
    at Object.step (audible-library-extractor-content-script.js:2)
    at audible-library-extractor-content-script.js:2
```

Image of the screen when it hangs up:
> ![image](https://user-images.githubusercontent.com/61511816/137785238-4feeca45-fe20-4c3c-b4d8-4445692f739b.png)

And the only other notice I see is 
```launch-3111109c87da.min.js:29 🚀 _satellite.notify is deprecated. Please use the `_satellite.logger` API.```
But this seems to be a Audible SEO issue not one with the plug in.

My thoughts are that it is the video on that page that might be causing the issue, but I am unsure on exactly how the extrntion operates to say that for sure that the video is the issue.
Link to page as per Curl
https://www.audible.com/pd/Ready-Player-One-Audiobook/B005FRGT44

Things atempted to resolve issue on my side

- Clear Browser Cache
- Clear DNS Cache
- Use in Incognito mode
- Uninstall and Reistall
- Install in another chrome session

Atached is the console log from chrome of one atempted run.

[www.audible.com-1634580026467.log](https://github.com/joonaspaakko/audible-library-extractor/files/7367634/www.audible.com-1634580026467.log)

Please let me know if you need me to run anything to get you more info if you are not able to repoduce it.

**Comment by joonaspaakko** [comment]
So while I think it was already fixed in that prior commit I've now (6555d2331c34b2500fa54804bec84aecbeaaa51a) improved it so it should never stop the extraction process by accident. Of course, that doesn't mean something else won't.

> Also, I kinda mentioned it already, but since v.0.2.6 I've added better error handling in certain places during the extraction, which alone should already get around certain issues where the extraction process would stop when it hits an error. So with that in mind, any fixes relating to this specific error were probably unnecessary in order to get through the extraction, but especially the improvements I just added help get as much data in as possible, whereas an error would more than likely drop out a whole lot of potential data.

@CatHerderCam, I've also updated the dist-zip. I'd like you to try it to see if that fixes the issue.
