### ISSUE TITLE
only pulling 20 books

### ISSUE THREAD

**Issue by cazter** [joonaspaakko/audible-library-extractor#72]
only pulling 20 of the books in my audible library.

**Comment by joonaspaakko** [comment]
I'll check the extraction process myself later today just to make sure there haven't been any breaking changes on the website... Does it go through the extraction process and open the gallery? If it doesn't open the gallery where does it stop (what does the progress say)? Could you try the extraction a few times just to see if it's always 20 and never more or less than that.

**Comment by cazter** [comment]
Appreciate you investigating this and working on a resolution.
