### ISSUE TITLE
Standalone gallery: saved with collections excluded (occasionally?) loads up blank

### ISSUE THREAD

**Issue by joonaspaakko** [joonaspaakko/audible-library-extractor#81]
The issue seems to be that it's still looking for the collections data file and that is causing some kinda conflict. Should be pretty easy to fix.

**Navigating to another page or refreshing the current page should get you around the issue.** 
> The only proper workaround in versions 0.2.7 and 0.2.8 would be to save the gallery with collections...

**Comment by christianboyle** [comment]
Yea, I just started experiencing this.

Initially there is a JS error in console that says the `collections.xxxxxx.js` is 404, but I'm seeing some other missing files too.

When I initially load the standalone page it redirects to `/*/library`, but shows `0` books. If I then click on `Library` in the header or reload the page then my books show up.

If you watch the Sources panel before and after reloading the page you'll see 4 files get added:

```
book.js
grid-view.js
book.css
grid-view.css
```
![2022-02-27_11-42-44AM](https://user-images.githubusercontent.com/1605754/155893425-ee88e4ad-b920-41e7-9171-9be617c7c639.png)
![2022-02-27_11-43-08AM](https://user-images.githubusercontent.com/1605754/155893426-5c08f247-a1e5-44d6-b972-74484b00c574.png)

**Comment by joonaspaakko** [comment]
@christianboyle, I think the other files were just a chain reacton to the missing collections file. The error happens before those files would be loaded... So they're not. I made a build of the extension that should have this issue fixed, if you want to try that. 

**It will most likely be at least a month before the next real release will come out and that is probably too generous of an estimate.** So if this is a big issue for you, you might as well do it now:

1. [Export your existing data](https://joonaspaakko.gitbook.io/audible-library-extractor/gallery/import-export-data) into a JSON file.
3. **Disable** the current extension (to avoid conflicts). No need to remove it, in fact it might be better to keep it.
4. Download this build [**audible-library-extractor-v0.2.8-issue81-hotfix.zip**](https://github.com/joonaspaakko/audible-library-extractor/files/8156871/audible-library-extractor-v0.2.8-issue81-hotfix.zip)
5. [Then follow these dev release installation instructions](https://github.com/joonaspaakko/audible-library-extractor#how-to-install-development-releases) (at the very bottom — expand: _read more..._), **except in step 0 use the file you downloaded above**.
6. [Import the old JSON data](https://joonaspaakko.gitbook.io/audible-library-extractor/gallery/import-export-data) 

> This build so was somewhat hastily checked, but it's the first fix since the last version so assuming the pages load fine, you shouldn't end up with more issues...

**Comment by christianboyle** [comment]
@joonaspaakko Awesome, this new hotfix build works as expected. Thanks for the quick fix!
