### ISSUE TITLE
Only pulling 1st page of library / 20 titles

### ISSUE THREAD

**Issue by Narwalrus** [joonaspaakko/audible-library-extractor#98]
Only the most recent 20 titles are being pulled from the library. 
I also tried adding all the titles to a collection and having that export and it also only pulled the most recent 20 books.

Tried on both Firefox / Edge without any other extensions enabled

**Comment by joonaspaakko** [comment]
@Narwalrus, haven't heard back from you and I moved this issue post from the documentation repository to the project repository, so I figured I'd try to ping you just in case you lost track of where the post was or something. I'm still waiting for a reply if you're willing to test it out.

**Comment by joonaspaakko** [comment]
Closed for inactivity.
